name: keeta
description: "Dart SDK to interact with the Keeta Network. Keeta is world’s most scalable layer-1 blockchain network. "
version: 0.0.1-dev.2
homepage: https://github.com/jagadeeshchoudhary/keeta
repository: https://github.com/jagadeeshchoudhary/keeta
issue_tracker: https://github.com/jagadeeshchoudhary/keeta/issues
documentation: https://github.com/jagadeeshchoudhary/keeta#readme
funding:
  - https://github.com/sponsors/jagadeeshchoudhary

environment:
  sdk: ^3.9.2

dependencies:
  asn1lib: ^1.6.5
  base32: ^2.2.0
  convert: ^3.1.2
  ed25519_edwards: ^0.3.1
  meta: ^1.17.0
  pointycastle: ^4.0.0
  secp256k1: ^0.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

license: MIT
